import React from 'react';
import {Link} from 'react-router';

export default class TripSummary extends React.Component{
  render(){
    return(
      //this.props.author._id
      //          .trip._id
      //          .start
      //          .destination
      //          .dates
      //          .summary
      <div className="panel panel-default user-generated">
        <div className="panel-body">
          <div className="media">
            <div className="media-top">
              <div className="row">
                <div className="col-md-6">
                  Generated By: <Link to={"/profile/" + this.props.author._id}>{this.props.author.fullName}</Link><br />
                  Start: {this.props.start}<br />
                  Destination: {this.props.destination}<br />
                  {this.props.dates}
                </div>
                <div className="col-md-6">
                  <div className="pull-right">
                    <button type="button" className="btn btn-default" onClick={<Link to={"/trip/" + this.props.trip._id}></Link>}>
                      <span className="glyphicon glyphicon-search"></span>
                      More Info
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div className="media-left"></div>
            <div className="media-body">
              <div className="form-group">
                <br />
                {this.props.summary}
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}
