import React from 'react';
export default
class TripSummary extends React.Component{
  render(){
    return(
          <div className="media">
            <div className="media-top">
              <div className="row">
                <div className="col-md-6">
                  Generated By: <a href="#">{this.props.author}</a><br />
                  Start: {this.props.start}<br />
                  Destination: {this.props.destination}<br />
                  {this.props.dates}
                </div>
                <div className="col-md-6">
                  <div className="pull-right">
                    <button type="button" className="btn btn-default">
                      <span className="glyphicon glyphicon-search"></span>
                      More Info
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div className="media-left"></div>
            <div className="media-body">
              <div className="form-group">
                <br />
                {this.props.summary}
              </div>
            </div>
          </div>
    )
  }
}
