import React from 'react';
import TripSummary from './tripsumdb';
import {Link} from 'react-router';
import {getModalTrips} from '../server';

export default class Modal extends React.Component{
  constructor(props) {
    super(props);
    this.state = {
      trip1: {},
      trip2: {},
      trip3: {}
    }
    this.refresh.bind(this);
  }

  refresh() {
    getModalTrips((feedData) => {
      this.setState(feedData);
    });
  }

  componentDidMount() {
    this.refresh();
  }
  render(){
    return(
        <div className="modal-dialog" role="document">
          <div className="modal-content">
            <div className="modal-header">
              <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h1 className="modal-title">Generated Vacations</h1>
            </div>
            <div className="modal-body">
              <ul className="media-list">
                <li>
                  <div className="media">
                    <div className="media-top">
                      <div className="row">
                        <div className="col-md-6">
                          Generated By: <a href="#">John Doe</a><br/>
                        Start: Amherst, MA<br/>
                      Destination: Boston, MA<br/>
                          Date: 6/24/2011 - 6/24/2011
                        </div>
                        <div className="col-md-6">
                          <div className="pull-right">
                            <Link to={"/full-trip/"}>
                              <button type="button" className="btn btn-default" data-toggle="modal" href="#generated">
                                <span className="glyphicon glyphicon-search"></span>
                                More Info
                              </button>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="media-left"></div>
                    <div className="media-body">
                      <div className="form-group">
                        <br/>
                        A day trip to Boston by car for under $300.
                        Destinations include the Boston Aquarium and Franklin Park Zoo.
                        Planned restaurants include Italian Express Pizzeria and
                        The Capital Grille.
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <span>Author: {this.state.trip1.contents.author}</span>
                </li>
              </ul>
            </div>
            <div className="modal-footer">
              <div className="text-center">
                  <h2>Don't like any of these?</h2>
                  <ul className="list-inline">
                    <li>
                      <button type="button" className="btn btn-primary btn-lg" data-toggle="modal" href="#generated">
                        Generate Again
                      </button>
                    </li>
                    <li> or </li>
                    <li>
                      <Link to={"/customize/"}>
                      <button data-toggle="modal" href="#generated" type="button" className="btn btn-primary btn-lg">
                        Customize Preferences
                      </button>
                      </Link>
                    </li>
                  </ul>
                </div>
            </div>
          </div>
        </div>
    )
  }
}
