import React from 'react';
import TripSummary from './tripsummary';
import {Link} from 'react-router';
import {getUserTrips} from '../server';

export default class UserGeneratedPage extends React.Component{
  constructor(props) {
    super(props);
      this.state = {
        trips: []
      };
  }
  refresh() {
      getUserTrips(1, (trips) => {
        this.setState({trips: Object.keys(trips).map(k => trips[k])});
    });
  }
  componentDidMount() {
    this.refresh();
  }

  render(){
    return (
      <div>
        <div className="panel panel-default user-generated">
          <div className="panel-body">
            <div className="media-top">
              <div className="row">
                <div className="col-md-12">
                  <h3>Trips Generated by <Link to={"/profile/"}>You</Link>:</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div>
          {this.state.trips.map((trip) => {
            return (
              /*<TripSummary key={trip._id}
                        author={trip.author}
                        trip={trip._id}
                        start={"Boston, MA"}
                        destination={"Washington DC"}
                        dates={"2/4/2014 - 2/10/2014"}
                        summary={"A 7 day trip to Washington DC by airplane for under $9000. Destinations include the Museum of Natural History and the National Air and Space Museum. Planned restaurants include We the Pizza and GrillFish."}>
              </TripSummary>*/
              <TripSummary key={trip._id}
                        author={trip.author}
                        trip={trip._id}
                        start={trip.start}
                        destination={trip.destination}
                        dates={trip.dates}
                        summary={trip.summary}>
              </TripSummary>
            )
          })}
        </div>
      </div>);
  }
}
