import React from 'react';
import TripSummary from './tripsumdb';
import {Link} from 'react-router';
import {getUserTrips} from '../server';

export default class UserGeneratedPage extends React.Component{
  constructor(props) {
    super(props);
      this.state = {
        trip1: {
          _id: 0,
          type: "TripSummaryItem",
          trip_id: 0,
          contents: {
            author: "",
            trip:0,
            start:"",
            destination:"",
            dates:"",
            summary: ""
          }
        },
        trip2: {
          _id: 0,
          type: "TripSummaryItem",
          trip_id: 0,
          contents: {
            author: "",
            trip:0,
            start:"",
            destination:"",
            dates:"",
            summary: ""
          }
        },
        trip3: {
          _id: 0,
          type: "TripSummaryItem",
          trip_id: 0,
          contents: {
            author: "",
            trip:0,
            start:"",
            destination:"",
            dates:"",
            summary: ""
          }
        }
      }
  }
  refresh() {
       getUserTrips((feedData) => {
         this.setState(feedData);
     });
  }
  componentDidMount() {
    this.refresh();
  }
  render(){
    return (
      <div>
        <div className="panel panel-default user-generated">
          <div className="panel-body">
            <div className="media-top">
              <div className="row">
                <div className="col-md-12">
                  <h3>Trips Generated by <Link to={"/profile/"}>You</Link>:</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div>
          <TripSummary key={this.state.trip1._id} data={this.state.trip1}/>
          <TripSummary key={this.state.trip2._id} data={this.state.trip2}/>
          <TripSummary key={this.state.trip3._id} data={this.state.trip3}/>
        </div>
      </div>);
  }
}
